### ISSUE TITLE
Bug when registering a department in profile route

### ISSUE THREAD

**Issue by alereca** [team120/Universiteams#166]
NewRelic error report: https://onenr.io/0bRmpqNgVwy

```
Cannot save, given value must be instance of entity class, instead object literal is given. Or you must specify an entity target to method call.
```

```
at /home/node/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:67:31
    at Array.forEach (<anonymous>)
    at /home/node/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:62:26
    at Array.map (<anonymous>)
    at EntityPersistExecutor.execute (/home/node/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:59:66)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthService.saveProfile (/home/node/app/dist/auth/auth.service.js:173:13)
    at async /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /home/node/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by alereca** [comment]
![Image](https://github.com/user-attachments/assets/03e2c7e0-f1d5-4963-845b-e66956bd2b10)
